// <auto-generated />
using System;
using AzureBootCamp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureBootCamp.Migrations
{
    [DbContext(typeof(AZBootcamp2021DBContext))]
    partial class AZBootcamp2021DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AzureBootCamp.Context.SessionLink", b =>
                {
                    b.Property<int>("SessionLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionLinkId"), 1L, 1);

                    b.Property<string>("SessionLinkValue")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("datetime");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("SessionLinkId");

                    b.HasIndex("TrackId");

                    b.ToTable("SessionLink", (string)null);
                });

            modelBuilder.Entity("AzureBootCamp.Context.Speaker", b =>
                {
                    b.Property<int>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeakerId"), 1L, 1);

                    b.Property<string>("SpeakerBio")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SpeakerDesignation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SpeakerImage")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speaker", (string)null);
                });

            modelBuilder.Entity("AzureBootCamp.Context.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("TopicDescription")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TopicImage")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TopicTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("TopicId");

                    b.HasIndex("TrackId");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("AzureBootCamp.Context.TopicSpeaker", b =>
                {
                    b.Property<int>("TopicSpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicSpeakerId"), 1L, 1);

                    b.Property<int>("SpeakerId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("TopicSpeakerId");

                    b.HasIndex("SpeakerId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicSpeaker", (string)null);
                });

            modelBuilder.Entity("AzureBootCamp.Context.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"), 1L, 1);

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TrackId");

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("AzureBootCamp.Context.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Company Name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Experience")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Tracks")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "IX_User")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AzureBootCamp.Context.SessionLink", b =>
                {
                    b.HasOne("AzureBootCamp.Context.Track", "Track")
                        .WithMany("SessionLinks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK_SessionLink_Track");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("AzureBootCamp.Context.Topic", b =>
                {
                    b.HasOne("AzureBootCamp.Context.Track", "Track")
                        .WithMany("Topics")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Track");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("AzureBootCamp.Context.TopicSpeaker", b =>
                {
                    b.HasOne("AzureBootCamp.Context.Speaker", "Speaker")
                        .WithMany("TopicSpeakers")
                        .HasForeignKey("SpeakerId")
                        .IsRequired()
                        .HasConstraintName("FK_TopicSpeaker_Speaker");

                    b.HasOne("AzureBootCamp.Context.Topic", "Topic")
                        .WithMany("TopicSpeakers")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FK_TopicSpeaker_Topic");

                    b.Navigation("Speaker");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AzureBootCamp.Context.Speaker", b =>
                {
                    b.Navigation("TopicSpeakers");
                });

            modelBuilder.Entity("AzureBootCamp.Context.Topic", b =>
                {
                    b.Navigation("TopicSpeakers");
                });

            modelBuilder.Entity("AzureBootCamp.Context.Track", b =>
                {
                    b.Navigation("SessionLinks");

                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
